from dataclasses import dataclass
from core.field import mod_inv


@dataclass(frozen=True)
class Point:
    x: int | None
    y: int | None
    infinity: bool = False


@dataclass(frozen=True)
class Curve:
    name: str
    p: int
    a: int
    b: int
    g: Point
    n: int
    h: int


def get_infinity() -> Point:
    return Point(None, None, True)


def get_p256_curve() -> Curve:
    p = 0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFF
    a = 0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFC
    b = 0x5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B

    gx = 0x6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296
    gy = 0x4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5

    n = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551
    h = 1

    g = Point(gx, gy)

    return Curve(
        name="P-256",
        p=p,
        a=a,
        b=b,
        g=g,
        n=n,
        h=h
    )


def is_on_curve(point: Point, curve: Curve) -> bool:
    if point.infinity:
        return True

    left = (point.y * point.y) % curve.p
    right = (point.x * point.x * point.x + curve.a * point.x + curve.b) % curve.p

    return left == right


def point_neg(point: Point, curve: Curve) -> Point:
    if point.infinity:
        return point

    return Point(point.x, (-point.y) % curve.p)


def point_add(p1: Point, p2: Point, curve: Curve) -> Point:
    if p1.infinity:
        return p2

    if p2.infinity:
        return p1

    if p1.x == p2.x and (p1.y != p2.y or p1.y == 0):
        return get_infinity()

    if p1.x == p2.x and p1.y == p2.y:
        slope = ((3 * p1.x * p1.x + curve.a) * mod_inv(2 * p1.y, curve.p)) % curve.p

    else:
        slope = ((p2.y - p1.y) * mod_inv(p2.x - p1.x, curve.p)) % curve.p

    x3 = (slope * slope - p1.x - p2.x) % curve.p
    y3 = (slope * (p1.x - x3) - p1.y) % curve.p

    return Point(x3, y3)


def scalar_mult(k: int, point: Point, curve: Curve) -> Point:
    if k % curve.n == 0 or point.infinity:
        # REVIEW:
        # maybe change 'k % curve.n == 0' to 'k == 0'
        # for usage if not in subgroup generated by G
        return get_infinity()

    if k < 0:
        return scalar_mult(-k, point_neg(point, curve), curve)

    result = get_infinity()

    addend = point

    while k > 0:
        if k & 1:
            result = point_add(result, addend, curve)

        addend = point_add(addend, addend, curve)
        k >>= 1

    return result
